export const siteConfig = {
  name: "Arun Acharya",
  siteName: "Arun Acharya Portfolio",
  url: "https://arunacharya1603.in",
  email: "arunacharya1603@gmail.com",
  x: "https://x.com/143rhry112645",
  github: "https://github.com/arunacharya1603",
  linkedin: "https://www.linkedin.com/in/arunacharya1603/",
  locale: "en_US",
  countryCode: "IN",
};

export const topSeoKeywords = [
  "freelance web developer",
  "small business website developer",
  "small website developer",
  "medium business website developer",
  "frontend revamp freelancer",
  "website redesign freelancer",
  "ui ux help for website",
  "api development freelancer",
  "full stack web app developer",
  "full-stack developer",
  "react developer",
  "next.js developer",
  "react next.js developer",
  "hire frontend developer",
  "next.js freelancer",
  "react developer for small business",
  "affordable website developer",
  "ui ux designer freelancer",
  "full stack developer for startup",
  "landing page developer",
  "web app developer",
  "SaaS developer freelancer",
  "dashboard developer",
];
