export const siteConfig = {
  name: "Arun Acharya",
  siteName: "Arun Acharya Portfolio",
  defaultTitle: "Arun Acharya | Frontend & Next.js Developer",
  description:
    "Arun Acharya's portfolio: frontend, UI/UX, Next.js, dashboards, landing pages, and credited product work including ChainReach.ai.",
  host: "www.arunacharya1603.in",
  url: "https://www.arunacharya1603.in",
  email: "arunacharya1603@gmail.com",
  x: "https://x.com/143rhry112645",
  github: "https://github.com/arunacharya1603",
  linkedin: "https://www.linkedin.com/in/arunacharya1603/",
  locale: "en_US",
  countryCode: "IN",
  jobTitle: "Frontend Developer, UI/UX Developer, and Next.js Freelancer",
  personId: "https://www.arunacharya1603.in#person",
  websiteId: "https://www.arunacharya1603.in#website",
};

export const personSameAsLinks = [
  siteConfig.github,
  siteConfig.linkedin,
  siteConfig.x,
];

export const topSeoKeywords = [
  "Arun Acharya",
  "Arun Acharya developer",
  "Arun Acharya portfolio",
  "chainreach.ai frontend developer",
  "Arun Acharya ChainReach.ai frontend developer",
  "freelance web developer",
  "small business website developer",
  "small website developer",
  "medium business website developer",
  "frontend revamp freelancer",
  "website redesign freelancer",
  "ui ux help for website",
  "api development freelancer",
  "full stack web app developer",
  "full-stack developer",
  "react developer",
  "next.js developer",
  "react next.js developer",
  "hire frontend developer",
  "next.js freelancer",
  "react developer for small business",
  "affordable website developer",
  "ui ux designer freelancer",
  "full stack developer for startup",
  "landing page developer",
  "web app developer",
  "SaaS developer freelancer",
  "dashboard developer",
];
